version: '3.9'
services:
  app:
    build:
      context: .
    container_name: tikishsara
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - datatbase
      - nginx
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=database
      - DATABASE_PORT=5432

  datatbase:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
volumes:
  postgres:
  static:
  media: